# Generated by Django 4.1.7 on 2026-09-02 20:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gruppe',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Gruppenname')),
                ('bild', models.ImageField(blank=True, null=True, upload_to='unvertraeglichkeiten/gruppen/', verbose_name='Gruppenbild')),
            ],
            options={
                'verbose_name': 'Gruppe',
                'verbose_name_plural': 'Gruppen',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Kategorie',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Kategoriename')),
                ('bild', models.ImageField(blank=True, null=True, upload_to='unvertraeglichkeiten/kategorien/', verbose_name='Kategoriebild')),
            ],
            options={
                'verbose_name': 'Kategorie',
                'verbose_name_plural': 'Kategorien',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Kind',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('farbe', models.CharField(default='#1976d2', max_length=7, verbose_name='Farbe')),
                ('gruppe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kinder', to='unvertraeglichkeiten.gruppe', verbose_name='Gruppe')),
                ('kategorien', models.ManyToManyField(blank=True, related_name='kinder', to='unvertraeglichkeiten.kategorie', verbose_name='Kategorien')),
            ],
            options={
                'verbose_name': 'Kind',
                'verbose_name_plural': 'Kinder',
                'ordering': ['farbe', 'name'],
            },
        ),
    ]
